### PR TITLE
Add IBM branding to loopback-cli

### PR DESCRIPTION
**Pull request by bajtos**
screen shot 2017-01-16 at 10 32 18

Connect to strongloop-internal/scrum-loopback#1028

### CODE REVIEW

**Comment by chandadharap** [comment]
LGTM. However, please do not merge to master until green light from me.

**Comment by chandadharap** [comment]
Amending my comment. Okay to merge to master but not release to npmjs.

**Comment by bajtos** [comment]
Updated with the new message, also fixed the log to localize the message.

@superkhau could you PTAL again please?

**Comment by chandadharap** [comment]
I see you put it in after "node ." But Meric and I agreed its the right place. Looks good. However lets shorten it, i had Meric review as well. Removed the reference to open source. New updated text below:

The API Connect team at IBM happily continues to develop, support and maintain LoopBack, which is at the core of API Connect. When your APIs need  robust management and security options, please check out http://ibm.biz/tryAPIC

**Comment by chandadharap** [comment]
LGTM

**Pull request merged**
