### PR TITLE
Fix spawn-sync warning

### PR DESCRIPTION
**Pull request by superkhau**
Update `yeoman-generator` to prevent spawn-sync warning.

### CODE REVIEW

**Comment by superkhau** [comment]
@ritch Review please. I just updated the version and it seems t get rid of the error.

**Comment by superkhau** [comment]
We'll get @cgole to review the fix after I merge this and do a release.

**Comment by raymondfeng** [comment]
LGTM

**Comment by superkhau** [comment]
@raymondfeng TY

**Pull request merged**
