### PR TITLE
Add z/OS Connect EE command

### PR DESCRIPTION
**Pull request by crshnburn**
### Description
Add a new command, `zosconnectee` to the `lb` command which:
1. Connects to the z/OS Connect EE server for a specified datasource
2. Retrieves the list of available APIs
3. Retrieves the Swagger document for the selected API and configures the Datasource

#### Related issues

- strongloop/loopback-cli#43

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by raymondfeng** [comment]
@crshnburn I'm not sure why your PR has commits that are not related to your change. How did you rebase your branch? Typically, you can rebase your branch to the latest master as follows:

1. git checkout your-branch
2. git pull --rebase origin master
3. git push -f

**Comment by crshnburn** [comment]
@raymondfeng I'm not sure either, I did the rebase as described, but omitted the `-f` on the original push. I've since backed that off, and forced the update from the original rebase.

**Comment by crshnburn** [comment]
Have raised PR strongloop/loopback-cli#43 to update the tests there that are failing due to this PR

**Comment by jannyHou** [comment]
@crshnburn Could you add some test for you command and make sure the CI tests pass?

**Comment by jannyHou** [comment]
hmm, now linux are failing due to 
```
  1) loopback:soap tests periodic table wsdl periodic table wsdl:
     Uncaught Error: Invalid WSDL URL: http://www.webservicex.net/periodictable.asmx?WSDL
```
Not caused by this PR though, don't worry.

**Comment by crshnburn** [comment]
New tests have been added to test `loopback:zosconnectee` though they do need loopback/workspace#491 to be available to work correctly.

**Comment by bajtos** [comment]
@jannyHou @raymondfeng @crshnburn what's the status of this pull request? Is it good to be landed now?

**Comment by bajtos** [comment]
@slnode test please

**Comment by raymondfeng** [comment]
@slnode test please

**Comment by raymondfeng** [comment]
ok to test

**Comment by raymondfeng** [comment]
@hacksparrow I'm seeing a test failure as follows for both master and this PR. Can you investigate?
```
1) loopback:datasource generator with --bluemix should support IBM Object Storage :
     Uncaught AssertionError: expected undefined to exist
      at test/datasource.test.js:280:70
```

**Comment by crshnburn** [comment]
Current failing test is the new one added as part of the review which requires strongloop/loopback-cli#43 in order to pass successfully.

**Comment by bajtos** [comment]
> Current failing test is the new one added as part of the review which requires strongloop/loopback-cli#43 in order to pass successfully.

This does not make sense to me - AFAIK, loopback-cli depends on generator-loopback, not the other way around.

AFAICT, the CI is failing because of a problem in your pull request, see e.g. https://travis-ci.org/strongloop/generator-loopback/jobs/289401867

```
 1) loopback:zosconnectee generator creates and configures CatalogManager API:
     Uncaught AssertionError: expected { Object (db) } to have a property 'zosconnectee'
      at test/zosconnectee.test.js:77:39
      at constructor.<anonymous> (node_modules/yeoman-generator/lib/base.js:411:5)
```

@crshnburn could you PTAL? Also while you are looking into this pull request, could you please rebase it on top of the latest master?

**Comment by crshnburn** [comment]
@bajtos I've updated the test to remove the issue where testing on it's own worked but running in the wider test bucket. The only failing check is now testing loopback-cli which needs strongloop/loopback-cli#43

**Comment by bajtos** [comment]
Thank you for the update, @crshnburn. I think the PR is good to be landed now.

@raymondfeng @jannyHou what's your opinion?

**Comment by bajtos** [comment]
I rebase the patch on top of the latest master and squashed all commits to a single one. Let's wait for green CI results before landing.

**Comment by bajtos** [comment]
Released in `generator-loopback@5.5.0`

**Pull request merged**
