### PR TITLE
Only show editable model names in remote-method generator

### PR DESCRIPTION
**Pull request by jannyHou**
I should update remote-method generator together in this commit: https://github.com/strongloop/generator-loopback/commit/326102606476eef244102aaaf9104237d03c7823

One line's change, could you review it @bajtos , thanks :)

### CODE REVIEW

**Comment by jannyHou** [comment]
@slnode test pleaes

**Comment by jannyHou** [comment]
@slnode test please

**Comment by bajtos** [comment]
LGTM.

@jannyHou after you land this patch, could you please check why `generator-loopback/node=0.12,os=windows ` is failing on CI?

**Comment by jannyHou** [comment]
@bajtos Thank you and sure I will take a look.

**Comment by jannyHou** [comment]
@slnode test please

**Pull request merged**
