### PR TITLE
Create Issue and PR Templates

### PR DESCRIPTION
**Pull request by ssh24**
Create Issue and PR Templates

### CODE REVIEW

**Comment by ssh24** [comment]
@slnode test please

**Comment by bajtos** [comment]
@ssh24 I am not sure why our CLA check is failing, would you mind signing the CLA so that I can land this pull request?

https://cla.strongloop.com/agreements/strongloop/generator-loopback

**Comment by ssh24** [comment]
@bajtos CLA signed. Looks like the branch is out of date as well but I cannot rebase since I do not have the access anymore. Feel free to takeover the branch and rebase for me.

**Comment by bajtos** [comment]
>  CLA signed.

Thank you!

> Looks like the branch is out of date as well but I cannot rebase since I do not have the access anymore. Feel free to takeover the branch and rebase for me.

Yeah, that's unfortunate. I'll take this work over.

**Comment by bajtos** [comment]
CI build failures are not related to this change.

**Pull request merged**
