### PR TITLE
Update strong-globalize require to 1 line

### PR DESCRIPTION
**Pull request by 0candy**

### CODE REVIEW

**Comment by 0candy** [comment]
@jannyHou PTAL

**Comment by jannyHou** [comment]
@0candy LGTM but I am confused why strings in `intl/en/messages.json` have some change? The pr doesn't contain refactor of message, are they changed due to algorithm changed in new version of strong-globalize?

**Comment by 0candy** [comment]
Janny, fixed spacing for this line.
"Add `{{Loopback Explorer }}`to the project ({{true}} by default)",

**Comment by jannyHou** [comment]
LGTM 👍 
I triggered a new build on master branch to see what's wrong with those two failing macOS:
http://ci.strongloop.com/job/generator-loopback/

**Comment by jannyHou** [comment]
And BTW, I think miroslav's pr does fix the `rmdir` error, at least in lb-workspace:
http://ci.strongloop.com/job/loopback-workspace/4735/
Now we only have one failing machine, looks like fail due to config problem, not code.

**Pull request merged**
