### PR TITLE
Remove 'slc arc' from post install log

### PR DESCRIPTION
**Pull request by joesepi**
@crandmck PTAL. Thanks! :)

cc @cfjedimaster @emckean

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
LGTM, but I think @chandadharap needs to approve.
cc @bajtos

**Comment by bajtos** [comment]
LGTM.

@joesepi please ping @chandadharap on Slack to get her approval faster.

**Comment by crandmck** [comment]
I just spoke with Chanda and she said this change was OK _if_ Sumitha  approves it.

**Comment by sumitha** [comment]
@aydonat please review. This is part of not making Arc use explicit since it is going to be deprecated. @joesepi as discussed we will look to what can be a suitable replacement if any for this line.

**Comment by sumitha** [comment]
LGTM.  Discussed with Meric on email, all good.

**Comment by crandmck** [comment]
@bajtos @0candy Would it be possible to please publish `generator-loopback` to npm, so this change is released?

**Comment by bajtos** [comment]
Done: `generator-loopback@1.25.0`

**Pull request merged**
