### PR TITLE
Use options from datasource to connect and get wsdl

### PR DESCRIPTION
**Pull request by ilijaz**
### Description

Use options from datasource to connect and get wsdl. For example, It uses for sending http auth header.

#### Related issues

- connect to https://github.com/strongloop/loopback-connector-soap/issues/92

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Thank you @ilijaz for the pull request! I am not familiar with this part of our codebase myself. @raymondfeng @rashmihunt could you please review?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by raymondfeng** [comment]
@ilijaz Good idea. 

Please fix the commit message per https://ci.sl.strongloop.com/job/strongloop-commit-linter-jobs/job/generator-loopback/455/console. The message is too long.

**Pull request closed without merging**
