### PR TITLE
Embbeded generator

### PR DESCRIPTION
**Pull request by kenzananram88**
#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
@kenzananram88 Can you explain what features are being proposed here?

**Comment by bajtos** [comment]
I am closing this pull request as abandoned. @kenzananram88 feel free to reopen if/when you get time to work on this again and answer Raymond's question above.

**Pull request closed without merging**
