### PR TITLE
Update spec-loader.js

### PR DESCRIPTION
**Pull request by abqadeer**
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@abqadeer , thanks for submitting a PR.  Could you please sign the CLA? 
https://cla.strongloop.com/agreements/strongloop/generator-loopback

@hacksparrow , could you please help reviewing this PR?  Thanks!

**Comment by dhmlau** [comment]
@abqadeer , your PR looks good to me.  Sorry that the branch is out of date again.  Could you please rebase it and i'll help you land.  Thanks!

**Comment by abqadeer** [comment]
Just updated the code @dhmlau ,please consider merging into master.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by virkt25** [comment]
@slnode test please

@dhmlau Travis Node 4 is failing because our dependencies (`yeoman-generator`) is now Node 6 and higher only. We can merge this and create a PR to drop Node 4 from this package and do a new version release.

**Comment by bajtos** [comment]
FWIW, it would be great to add a unit test to verify this fix and prevent regressions in the future. See [test/swagger.test.js](https://github.com/strongloop/generator-loopback/blob/79659ac1e40f1936b581920d5848b63ef697c1c8/test/swagger.test.js).

**Pull request closed without merging**
