### PR TITLE
Remove slc:loopback-example

### PR DESCRIPTION
**Pull request by 0candy**
https://github.com/strongloop-internal/scrum-loopback/issues/652

### CODE REVIEW

**Comment by 0candy** [comment]
@bajtos Please review.

**Comment by bajtos** [comment]
@0candy Nice, LGTM.

Two nitpicks: we usually don't reference GH issues in commit messages. I.e. `Remove slc:loopback-example` would be a better title.

OTOH, we do reference issues in GH pull request description, to make the GH issue one link/click away. I added that myself here.

**Comment by bajtos** [comment]
Eh, ignore the last sentence, you have already connected this PR to the isuse.

**Comment by bajtos** [comment]
> we usually don't reference GH issues in commit messages. I.e. Remove slc:loopback-example would be a better title.

Especially since `652` is not enough to identify the GH issue living in a different project.

Please amend the commit and fix the message.

**Comment by 0candy** [comment]
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/652

**Pull request merged**
