### PR TITLE
Fix generator not adding remote-method to json file

### PR DESCRIPTION
**Pull request by 0candy**
Connect to https://github.com/strongloop/generator-loopback/issues/222

### CODE REVIEW

**Comment by 0candy** [comment]
@jannyHou @bajtos PTAL

**Comment by jannyHou** [comment]
LGTM.

**Comment by bajtos** [comment]
LGTM, :ship: 

Do we know why MacOS tests failed? How can we prevent these failures in the future?

**Comment by 0candy** [comment]
A few failures on installing dependencies.

**Pull request merged**
