### PR TITLE
WIP: Add loopback:component generator

### PR DESCRIPTION
**Pull request by raymondfeng**
/to @ritch @bajtos 

WIP for testing, please do not merge.

### CODE REVIEW

**Comment by listepo** [comment]
+1

**Comment by listepo** [comment]
Hi need help?

**Comment by listepo** [comment]
Ping

**Comment by bajtos** [comment]
> Hi need help?

Hi @listepo, thanks for the offer. As I see it, the work of adding component generator should start in loopback-workspace, where we need to create a new project template. Then the next step is to use that template in generator-loopback and refactor `app/index` and the new `component/index` to share as much code as possible.

Having said that, this task is rather low in our priorities at the moment, and I won't have much time to help you along the way.

**Comment by superkhau** [comment]
@raymondfeng 2 year old PR, is this still relevant? Safe to close?

**Pull request closed without merging**
